# Generated by Django 4.2.2 on 2023-07-15 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profilemodel_image_profilemodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
